---
name: gomod-go-version-updater-action
'on': push
# 'on':
#   schedule:
#     - cron: '42 6 * * *'
permissions:
  contents: write
  pull-requests: write
jobs:
  gomod-go-version-updater-action:
    runs-on: ubuntu-22.04
    steps:
      - uses: 030/gomod-go-version-updater-action@21-create-pr-only-if-not-exists
#
